### ISSUE TITLE
Desarrollar la segunda opcion del menu.

### ISSUE THREAD

**Issue by GBPardoGabrielaBeatriz** [GBPardoGabrielaBeatriz/adj-Repositorio#2]
TAREA:
Se requiere desarrollar la opcion numero 2 del menu propuesto en el codigo.

Descripcion :
Estamos realizando consultas a una API publica relacionada a la bibliografia de Stephen King, y a la vez, guardando los resultados en una base de datos pertinente. La idea es proponer tambien la opcion de que el usuario  visualice la busqueda ya realizada anteriormente (Si es que ha echo alguna).

Se requiere :

Implementar algun metodo que liste los nombres de los libros buscados ya previamente.
Realizar Pruebas: Ejecutar pruebas para confirmar que el listado de los libros se visualice correctamente.
Actualizar Documentación: Actualizar la documentación del proyecto para reflejar los cambios realizados .
😊 Contribuciones:
Las contribuciones son bienvenidas. Sigue estos pasos solamente:

Haz un fork del proyecto.
Crea una nueva rama (git checkout -b feature/nueva-funcionalidad).
Realiza tus cambios y haz commit (git commit -m 'Añadir nueva funcionalidad').
Sube tus cambios a tu repositorio (git push origin feature/nueva-funcionalidad).
Crea un nuevo Pull Request.

**Comment by PabloSanchez87** [comment]
Hola!

He realizado un PR para los issues que tenías solicitados. 

He usado un codespace de github, por eso vas a encontrar un archivo de docker-compose porque he tenido que configurar el entorno para poder trabajar con java17 y mysql y para ello he utilizado docker.

Espero que con esto ya puedas realizar la tarea.

Un saludo!
